/* Generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "mood-music-generator",
  "name": "Mood Synth",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Rainy café at midnight, slow and jazzy",
      "does": "Composes a new piece for that mood and plays it."
    },
    {
      "say": "Slower, and swap the lead for something softer",
      "does": "Changes the tempo and lead sound."
    },
    {
      "say": "Save this to my library",
      "does": "Stores the piece with its mood."
    }
  ]
};
